In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('water.txt', sep='\t')

In [3]:
data[:5]

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [4]:
data.corr()

mortality  hardness
mortality   1.000000 -0.654849
hardness   -0.654849  1.000000

In [5]:
data.corr(method='spearman')

mortality  hardness
mortality   1.000000 -0.631665
hardness   -0.631665  1.000000

# 3

In [6]:
data_south = data[data['location']=='South']
data_north = data[data['location']=='North']

In [7]:
data_south.corr()

mortality  hardness
mortality   1.000000 -0.602153
hardness   -0.602153  1.000000

In [9]:
data_north.corr()

mortality  hardness
mortality   1.000000 -0.368598
hardness   -0.368598  1.000000

# 4

In [10]:
from scipy.stats import chi2, chi2_contingency

In [31]:
women_freq = 203
men_freq = 239

women_rare = 718
men_rare = 515

from math import *
mcc = float(women_freq*men_rare-women_rare*men_freq)/sqrt((women_freq+women_rare)*(men_freq+men_rare)*(women_freq+men_freq)*(women_rare+men_rare))
mcc

-0.10900237458678963

# 5

In [14]:
import numpy as np
ct = np.array([[women_freq, women_rare],[men_freq, men_rare]])
ct

array([[203, 718],
       [239, 515]])

In [15]:
chi2_contingency(ct)

(19.407530788543038,
 1.0558987006638725e-05,
 1L,
 array([[ 243.03402985,  677.96597015],
        [ 198.96597015,  555.03402985]]))

# 6

In [19]:
n_men = float(men_freq+men_rare)
n_women = float(women_freq+women_rare)
p_men = men_freq/n_men
p_women = women_freq/n_women
p_men-p_women

0.09656353231552606

In [20]:
from scipy.stats import norm
lb = p_men-p_women - norm.ppf(0.975)*sqrt(p_men*(1-p_men)/n_men+p_women*(1-p_women)/n_women)
ub = p_men-p_women + norm.ppf(0.975)*sqrt(p_men*(1-p_men)/n_men+p_women*(1-p_women)/n_women)
print lb, ub

0.0539052332158 0.139221831415


# 7

In [22]:
p = (p_men*n_men+p_women*n_women)/(n_men+n_women)
z = (p_men-p_women)/sqrt(p*(1-p)*(1/n_men+1/n_women))
print z
print 2*(1-norm.cdf(z))

4.46111444482
8.15345308958e-06


# 8, 9

In [23]:
ct = np.array([[197, 111, 33], [382, 685, 331], [110, 342, 333]])

In [25]:
res = chi2_contingency(ct)
res

(293.68311039689746,
 2.4964299580093467e-62,
 4L,
 array([[  93.08597464,  153.74722662,   94.16679873],
        [ 381.6251981 ,  630.318542  ,  386.0562599 ],
        [ 214.28882726,  353.93423138,  216.77694136]]))

# 10

In [30]:
vc = np.sqrt(res[0]/(ct.sum()*2))
vc

0.2412013934500338