In [28]:
from scipy.stats import binom_test, binned_statistic_2d, chisquare

In [5]:
binom_test(67, 100, 0.75, 'two-sided')

0.082222588913866079

In [6]:
binom_test(22, 50, 0.75, 'two-sided')

3.4831478978300243e-06

In [7]:
import pandas as pd

In [11]:
data = pd.read_csv('pines.txt', sep='\t')

In [12]:
data[:5]

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [21]:
import numpy as np
binx = np.linspace(0, 200, num = 6)
biny = np.linspace(0, 200, num = 6)
res = binned_statistic_2d(data['sn'], data['we'], None, statistic='count', bins=[binx, biny])

In [27]:
print res.statistic
print data.shape

[[ 18.  26.  29.  25.  20.]
 [ 14.  12.  22.  34.  25.]
 [ 12.  24.  15.  50.  37.]
 [  8.  19.  31.  50.   7.]
 [  7.   8.  37.  27.  27.]]
(584, 2)


In [36]:
f_exp = np.ones((25,))*23.36
f_exp
f_obs = res.statistic.reshape((25,))

In [37]:
chisquare(f_obs, f_exp, ddof=0)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.5746697749672791e-20)